export enum OddEnum {
  home_win = "MS 1",
  draw = "MS X",
  away_win = "MS 2",
  one_and_half_under = "1.5 ALT",
  one_and_half_over = "1.5 ÜST",
  two_and_half_under = "2.5 ALT",
  two_and_half_over = "2.5 ÜST",
  three_and_half_under = "3.5 ALT",
  three_and_half_over = "3.5 ÜST",
  no_mutal_goal = "KG YOK",
  yes_mutal_goal = "KG VAR",
  first_half_home_win = "İY 1",
  first_half_draw = "İY X",
  first_half_away_win = "İY 2",
  match_result = "Maç Sonucu",
  total_goal_under_over = "Toplam Gol Alt/Üst",
  mutual_yes_no = "Karşılıklı Gol Yok/Var",
  first_half_result = "İlk Yarı Sonucu",
  double_chance = "Çifte Şans",
  total_goal_odd_even = "Toplam Gol Tek/Çift",
  double_chance_home_draw = "ÇS 1-X",
  double_chance_away_draw = "ÇS X-2",
  total_goal_odd = "Tek",
  total_goal_even = "Çift",
}
